parameters:
    db_driver: pdo_mysql
    db_host: 172.16.0.222
    db_port: 3306
    db_name: craigray_core
    db_user: craigray_core
    db_password: 'U!f}6?]V*1Qi'
    db_prefix: bee_
    db_server: mysql