parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   '%db_driver%'
                host:     '%db_host%'
                port:     '%db_port%'
                dbname:   '%db_name%'
                user:     '%db_user%'
                password: '%db_password%'
                charset:  'utf8mb4'
                server_version: '5.7'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine'
                        prefix: 'App\Entity'
                        alias: App
