security:
    encoders:
        Hillrange\Security\Entity\User:
           algorithm: bcrypt
           cost:      '%encoder.cost%'
    providers:
        hillrange_security_user_provider:
            entity:
                class:  Hillrange\Security\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path:           login
                check_path:           login
                csrf_parameter:       'login[_token]'
                csrf_token_id:        authenticate
                csrf_token_generator: security.csrf.token_manager
                username_parameter:   'login[_username]'
                password_parameter:   'login[_password]'
                success_handler:      Hillrange\Security\Listener\SuccessHandler
            provider:                 hillrange_security_user_provider
            logout:
                path:                 logout
                target:               home
            remember_me:              false
#                secret:               '%env(APP_SECRET)%'
#                name:                 '%session_name%_remember_me'
#                lifetime:             43200 # 12 hours in seconds
#                path:                 /
#                secure:               false
#                remember_me_parameter: 'login[_remember_me]'
            switch_user:              true
    role_hierarchy:
        ROLE_USER: ~
        ROLE_ALLOWED_TO_SWITCH: ~
        ROLE_PARENT: ~
        ROLE_STUDENT: ~
        ROLE_STAFF: ~
        ROLE_TEACHER:
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_STUDENT
            - ROLE_STAFF
        ROLE_HEAD_TEACHER:
            - ROLE_TEACHER
        ROLE_PRINCIPAL:
            - ROLE_HEAD_TEACHER
        ROLE_ADMIN:
            - ROLE_ALLOWED_TO_SWITCH
        ROLE_REGISTRAR:
            - ROLE_PRINCIPAL
            - ROLE_ADMIN
        ROLE_SYSTEM_ADMIN:
            - ROLE_REGISTRAR
            - ROLE_PARENT
