parameters:
    mailer_transport: gmail
    mailer_host: smtp.gmail.com
    mailer_user: craig@craigrayner.com
    mailer_password: oaerkkeodcrjyhzw
    mailer_port: null
    mailer_encryption: null
    mailer_auth_mode: null
    mailer_sender_name: 'Busybee System'
    mailer_sender_address: craig@craigrayner.com
swiftmailer:
    url: '%env(MAILER_URL)%'
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
