twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/vendor/hillrange/security/templates': hillrange_security
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
