twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates/bundles/HillrangeSecurity': hillrange_security
        '%kernel.project_dir%/vendor/hillrange/security/Resources/views': hillrange_security
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
