# config/packages/dev/web_profiler.yaml
web_profiler:
    toolbar:              '%kernel.debug%'
    intercept_redirects:  true
    excluded_ajax_paths:  ^/bundles|^/_wdt

framework:
    profiler:
        enabled: '%kernel.debug%'