App\Entity\RollGroup:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - nameShort
                - calendarGroup
            message: calendar.group.nameshort.unique
            errorPath: nameShort
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - name
                - calendarGroup
            message: calendar.group.sequence.unique
            errorPath: name
        - App\People\Validator\UniqueStudentRoll: ~
    properties:
        website:
            - Url: ~
        name:
            - NotBlank: ~
        nameShort:
            - NotBlank: ~
        calendarGroup:
            - NotBlank: ~