App\Entity\CalendarGroup:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - name_short
                - calendar_group_id
            message: calendar.group.nameshort.unique
            errorPath: nameShort
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - name
                - calendar_group_id
            message: calendar.group.sequence.unique
            errorPath: name
    properties:
        website:
            - Url: ~
        name:
            - NotBlank: ~
        nameShort:
            - NotBlank: ~
